### ISSUE TITLE
Error when running on self-hosted

### ISSUE THREAD

**Issue by mrexox** [repo-sync/pull-request#34]
When I run this action on self-hosted runner, I get the following error:
```
Run repo-sync/pull-request@v2
/usr/bin/docker run --name cd3395d146bea0da2d51c305be69_a232a7 --label 765292 --workdir /github/workspace --rm -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_BRANCH -e INPUT_PR_TITLE -e INPUT_PR_BODY -e INPUT_PR_LABEL -e INPUT_GITHUB_TOKEN -e INPUT_PR_TEMPLATE -e INPUT_PR_REVIEWER -e INPUT_PR_ASSIGNEE -e INPUT_PR_MILESTONE -e INPUT_PR_DRAFT -e INPUT_PR_ALLOW_EMPTY -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/opt/actions-runner/_work/_temp/_github_home":"/github/home" -v "/opt/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/opt/actions-runner/_work/test-github-actions/test-github-actions":"/github/workspace" 765292:2070cd3395d146bea0da2d51c305be69
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Could you, please, tell, what the problem may it be with?

**Comment by wei** [comment]
did you run actions/checkout@v2 before this action?

**Comment by wei** [comment]
Closed due to inactivity.

**Comment by ericknyoto** [comment]
I got this exactly the same error also.
I also already ran actions/checkout@v2 before this actions.

Is this have something to do with github token?

**Comment by chrismowbraybv** [comment]
Im seeing this issue still

```
| fatal: not a git repository (or any parent up to mount point /Users/***)
| Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by xwchris** [comment]
same problem in self-hosted

**Comment by wei** [comment]
@xwchris  can you check the git version as well as provide logs?

**Comment by Simon-Gau** [comment]
I faced this issue, shed blood, sweat and tears and found the solution. It is pretty silly but a bit of a trap/silent error. I will leave it to posterity since it was quite the rabbit hole.

This action was ran from a job that was set to use a docker image that has an old git version. Basically to diagnose the problem, look at the checkout action's logs. If you see the following :

` The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH`

Well it means that your git is either incorrectly installed or older than 2.18. From what I understand, if your git version is older than 2.18, it just dumps you a tarball instead of properly cloning.

So verify that your git version is at least 2.18, not only on your GitHub runner root host, but also in whichever container runs the checkout action. To quickly test it out you can run apt-get commands to upgrade git right before your checkout action, which should run before this repo's action.
